### PR TITLE
Improve descriptions of duplicates

### PR DESCRIPTION
**Pull request by ferki**
This PR is a proposal to improve the description of detected cases of duplicate literals and subroutines.

The current description of those violations include the line and column numbers, which I often found too verbose with default settings of perlcritic. Whenever that information is required, it can be obtained by choosing an appropriate [`--verbose` format](https://metacpan.org/dist/Perl-Critic/view/bin/perlcritic#-verbose-N-|-FORMAT) for `perlcritic` that includes `%l` and/or `%c` in its format specification.

According to the documentation of [description of Perl::Critic::Violation](https://metacpan.org/pod/Perl::Critic::Violation#description())

> this value may change on a per violation basis

so I propose to let the message include the actual literal that is detected as a duplicate.

Please review and merge, or let me know how to improve it further.

ps.: I wasn't sure how you would prefer to include this in `Changes`, so I left that out for now.

### CODE REVIEW

**Comment by ferki** [comment]
I noticed that the ProhibitDuplicateSub policy might not benefit too much from the originally proposed change, so I updated this PR to modify only ProhibitDuplicateLiteral (and included a changelog entry as well).

**Comment by gugod** [comment]
> ps.: I wasn't sure how you would prefer to include this in Changes, so I left that out for now.

I appreciate including a brief in `Changes` -- saves me all the hassles when doing CPAN releases :) The group of [line-bot-sdk-perl](https://github.com/line/line-bot-sdk-perl) developers has been doing this for a while now.

**Review by gugod — APPROVED** [review]
I didn't quite paying attention to the convention of "verbose" option of perlcritic when I wrote these policies ... the exclusion of line numbers makes sense since that can be globally enabled by either how `perlcritic` is invoked.

**Comment by ferki** [comment]
Thanks for merging, @gugod!

> > ps.: I wasn't sure how you would prefer to include this in Changes, so I left that out for now.
> 
> I appreciate including a brief in `Changes` -- saves me all the hassles when doing CPAN releases :)

Oh, yes, I'm all up for maintaining a changelog :)

I was just confused what to write in it for the first version of this PR, because I originally changed both `ProhibitDuplicateLiteral` and `ProhibitDuplicateSub`. I was wondering: should it be on two lines with the same message duplicated or one line with a comma separated list of modules changed?

Anyway, later I updated the PR to only touch `ProhibitDuplicateLiteral` for now, and I could add a changelog entry for that.

**Pull request merged**
